services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.test
    volumes:
      - .:/app
      - /app/node_modules
      - ../../packages/shared:/app/node_modules/@lib/shared
    depends_on:
      db_test:
        condition: service_healthy

  db_test:
    container_name: ${PROJECT_NAME}_db_test
    image: postgres:16-alpine
    restart: 'no'
    env_file:
      - ./.env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT:-5433}:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 2s
      timeout: 5s
      retries: 10