FROM node:22-alpine

WORKDIR /app

# Instala git e dependências do sistema necessárias
RUN apk add --no-cache openssl libc6-compat git

# Copia os arquivos de dependência
COPY package*.json ./

# Instala todas as dependências (baixa do GitHub)
RUN npm install

# Copia o Prisma e gera o client com a URL fake (necessário para o TS não reclamar dos tipos)
COPY prisma ./prisma
ARG DATABASE_URL="postgresql://fake:fake@localhost:5432/db"
ENV DATABASE_URL=$DATABASE_URL
RUN npx prisma generate

# Copia o resto do código fonte
COPY . .

# Em dev, não fazemos "npm run build". 
# O container vai iniciar rodando o script de dev (tsx watch)
CMD ["npm", "run", "dev"]